name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!",
  date_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Get date
        run: |
            date",
  directory_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Print directory
        run: |
            ls -l"